In [4]:
import numpy as np

In [33]:
x = np.array([1.0, 2.0, 3.0])

In [34]:
print(x)

[1. 2. 3.]


In [11]:
print(x[0], x[1], x[2])
print(type(x))

(1.0, 2.0, 3.0)
<type 'numpy.ndarray'>


In [12]:
print(np.ndim(x))

1


In [13]:
print(x.ndim)

1


In [14]:
print(x.shape)

(3,)


In [15]:
print(x.shape[0])

3


In [16]:
print(x.dtype)

float64


In [17]:
x1 = x.astype(np.float32)

In [18]:
print(x1)

[1. 2. 3.]


In [19]:
print(x1.dtype)

float32


In [20]:
x2 = np.array([1, 2, 3], dtype = np.float32) 

In [21]:
print(x2)

[1. 2. 3.]


In [22]:
print(x2.dtype)

float32


In [23]:
y = np.array([2., 4., 6. ])

In [24]:
print(x+y)
print(x-y)
print(x*y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [27]:
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [28]:
print(x.dot(y))
print(np.dot(x, y))

28.0
28.0


In [30]:
np.eye(4).dtype

dtype('float64')

In [5]:
A = np.array([[1,2,3], [4,5,6]], dtype = np.float32)

In [6]:
print(A)

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
print(A.ndim)
print(A.shape)
print(A.shape[0])
print(A.dtype)
print(A[1])

2
(2, 3)
2
float32
[4. 5. 6.]


In [8]:
for row in A:
    print(row)

[1. 2. 3.]
[4. 5. 6.]


In [9]:
B = np.array([[0.1,0.2,0.3], [0.1,0.2,0.3]])

In [10]:
print(A + B)
print(np.add(A,B))

[[1.1 2.2 3.3]
 [4.1 5.2 6.3]]
[[1.1 2.2 3.3]
 [4.1 5.2 6.3]]


In [11]:
print(A * B)
print(np.multiply(A,B))

[[0.1 0.4 0.9]
 [0.4 1.  1.8]]
[[0.1 0.4 0.9]
 [0.4 1.  1.8]]


In [12]:
print(A* np.full((2,3), 10))

[[10. 20. 30.]
 [40. 50. 60.]]


In [13]:
print(B.T)

[[0.1 0.1]
 [0.2 0.2]
 [0.3 0.3]]


In [17]:
print(A.dot(B.T))

[[1.4 1.4]
 [3.2 3.2]]


In [19]:
print(np.dot(A, B.T))

[[1.4 1.4]
 [3.2 3.2]]


In [21]:
print(np.dot(B.T, A))

[[0.5 0.7 0.9]
 [1.  1.4 1.8]
 [1.5 2.1 2.7]]


In [22]:
v = np.array([0.1,0.2,0.3])
w = np.array([1,4])

In [23]:
print(A.dot(v))

[1.4 3.2]


In [24]:
print(v.dot(B.T))

[0.14 0.14]


In [25]:
a = np.zeros((2, 3))

In [26]:
b = np.ones((1, 4))

In [27]:
print(a, b)

(array([[0., 0., 0.],
       [0., 0., 0.]]), array([[1., 1., 1., 1.]]))


In [29]:
e = np.random.random((3, 4))
print(e)

[[0.11344979 0.18620316 0.18953609 0.53341054]
 [0.33103544 0.76446934 0.9362638  0.75601677]
 [0.11877402 0.50271984 0.37230062 0.50489909]]


In [31]:
f = np.arange(0, 1, 0.2)
print(f)

[0.  0.2 0.4 0.6 0.8]


In [36]:
print(np.tan(x))

[ 1.55740772 -2.18503986 -0.14254654]


In [38]:
print(A)
print(np.sum(A))
print(np.sum(A, axis = 0))
print(np.sum(A, axis = 1))

[[1. 2. 3.]
 [4. 5. 6.]]
21.0
[5. 7. 9.]
[ 6. 15.]


In [39]:
C = B.flatten()

In [40]:
C

array([0.1, 0.2, 0.3, 0.1, 0.2, 0.3])

In [41]:
p = np.arange(0, 1, 0.1)

In [44]:
p = p.reshape((5, 2))

In [45]:
p

array([[0. , 0.1],
       [0.2, 0.3],
       [0.4, 0.5],
       [0.6, 0.7],
       [0.8, 0.9]])

In [47]:
q = np.arange(1,2, 0.1).reshape((5,2))
print(q)

[[1.  1.1]
 [1.2 1.3]
 [1.4 1.5]
 [1.6 1.7]
 [1.8 1.9]]


In [48]:
print(np.concatenate((p,q), axis = 1))

[[0.  0.1 1.  1.1]
 [0.2 0.3 1.2 1.3]
 [0.4 0.5 1.4 1.5]
 [0.6 0.7 1.6 1.7]
 [0.8 0.9 1.8 1.9]]


In [49]:
print(C)

[0.1 0.2 0.3 0.1 0.2 0.3]


In [50]:
C > 0.15

array([False,  True,  True, False,  True,  True])

In [54]:
C[C > 0.15] -= 0.15
print(C)

[0.1  0.05 0.15 0.1  0.05 0.15]


In [55]:
D = np.arange(1, 13, 1).reshape((3, 4))
print (D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
D1 = D[:2, 1:3]

In [57]:
D1

array([[2, 3],
       [6, 7]])

In [59]:
print(D[0][0], D[0][1], D[1][0], D[2][3])
print(D[0,0], D[0,1], D[1,0], D[2,3])

(1, 2, 5, 12)
(1, 2, 5, 12)


In [61]:
print(np.array([D[0,0], D[0,1], D[1,0], D[2,3]]))

[ 1  2  5 12]


In [62]:
print(D[[0,0,1,2], [0,1,0,3]])

[ 1  2  5 12]


In [63]:
u = np.array([1, 0, 1])
U = np.tile(u, [4, 1])

In [64]:
U

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [66]:
U.reshape((6,2))

array([[1, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 1],
       [0, 1]])